Ft periodic reports #145027463
andela/Healthchecks_Yosemite pull request #13
Opened 2017-06-04 19:29 UTC by jimmykimani

2017-06-04 19:31 UTC, jimmykimani commented
@andela-lkabui Done

2017-06-05 18:47 UTC, lewisemm requested changes

2017-06-05 18:47 UTC, andela-lkabui commented on hc/api/tests/test_send_reports.py
> +from datetime import timedelta
@jimmykimani All the changes you have made so far are related to the `hc/accounts` folder. Any reason why the tests located in `hc/api`?

2017-06-05 18:47 UTC, andela-lkabui commented on hc/api/tests/test_send_reports.py
> +        self.profile.report_duration = 1
What is this statement meant to do? I'm asking because `Profile` doesn't have a "report_duration" attribute.

2017-06-05 18:47 UTC, andela-lkabui commented on templates/accounts/profile.html
> +                <table class="table">
Fix the indentation here

2017-06-05 18:47 UTC, andela-lkabui commented on templates/accounts/profile.html
> +                <p>
Fix the indentation for this block

2017-06-05 18:47 UTC, andela-lkabui commented on templates/accounts/profile.html
> +                    <button type="submit" name="show_api_key" class="btn btn-default pull-right">Show API key</button>
Fix the indentation here

2017-06-05 18:47 UTC, andela-lkabui commented on templates/accounts/profile.html
> +            <div class="panel-body settings-block">
Fix the indentation here

2017-06-05 18:47 UTC, andela-lkabui commented on hc/api/tests/test_send_reports.py
> +from datetime import timedelta
These tests don't seem to be testing the functionality you added (weekly and daily reports)

2017-10-12 07:41 UTC, closed without merging